name: run main.py

on:
    schedule:
        - cron: '*/5 * * * *'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:

            - name: checkout repo contenr
              uses: actions/checkout@v2
        
            - name: setup python
              uses: actions/setup-python@v4
              with:
                python-version: '3.9'

            - name: install python packages
              run: |
                python -m pip install --upgrade pip
                pip install opencv-python
            
            - name: execute py script
              env:
                IMAGE_KEY: ${{ secrets.IMAGE_KEY }}
                USER_ID: ${{ secrets.USER_ID }}
                TOKEN: ${{ secrets.TOKEN }}
              run: python main.py
